export enum apiRoutes {
  LOGIN = '/auth/login',
  SIGNUP = '/auth/signup',
  SIGNOUT = '/auth/signout',
  ME = '/users/me',
  REFRESH_TOKENS = '/auth/refresh',
  FETCH_USERS = '/users',
  USERS_PREFIX = '/users',
  UPLOAD_AVATAR_IMAGE = '/users/upload',
  GET_AVATAR_IMAGE = '/users/get/image',
  ME_LOCATIONS = 'locations/me',
  LOCATIONS_PREFIX = '/locations',
  UPDATE_LOCATION = '/locations',
  ME_GUESSES = '/guesses/me',
} 