export enum routes {
  LOGIN = '/login',
  SIGNUP = '/signup',
  HOME = '/',
  USERINFO = '/me',
  USEREDIT = '../me/edit',
  USERPASSWORDEDIT = '../me/update-password',
  USERAVATAREDIT = '../me/update-avatar',
  ADDNEWLOCATION = '../me/mylocation',
  USERLOCATIONSINFO = '../me/locations',
  ALLLOCATIONS = '/locations',
  EDITLOCATION = '../../me/mylocation/edit',
  DELETELOCATION = 'me/mylocation/delete',
  MAKEGUESS = '../../guess/location',
  ALLGUESSES = '/guesses',
}
