export enum routes {
  LOGIN = '/login',
  SIGNUP = '/signup',
  HOME = '/',
  USERINFO = '/me',
  USEREDIT = '../me/edit',
  USERPASSWORDRESET = '../me/reset-password',
  USERAVATAREDIT = '../me/update-avatar',
  ADDNEWLOCATION = '../me/mylocation/add',
  USERLOCATIONSINFO = '../me/profile',
  ALLLOCATIONS = '/locations',
  EDITLOCATION = '../../me/mylocation/edit',
  DELETELOCATION = 'me/mylocation/delete',
  MAKEGUESS = '../../guess/location',
  ALLGUESSES = '/guesses',
}
